server:
  port: ${APPLICATION_PORT}
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: MultiService
  output:
    ansi:
      enabled: DETECT

info:
  java-vendor: ${java.specification.vendor}
  java-runtime-name: ${java.runtime.name}
  java-runtime-version: ${java.runtime.version}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    logfile:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: INFO
